version: '3'


services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_DATABASE: root
      MYSQL_DATABASE: nest
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306

  redis:
    image: redis:latest
    